// ====================================================================
// قاعدة بيانات الأسهم السعودية — مضاربة واستثمار
// ====================================================================

export type SignalType = "دخول" | "انتظر" | "خروج";
export type RiskLevel  = "منخفض" | "متوسط" | "عالي";
export type StockTier  = "قيادي" | "نمو" | "عوائد" | "خشاش";
export type StockType  = "speculation" | "investment";

export interface StockDef {
  symbol:       string;        // 4-digit Tadawul code
  yfSymbol:     string;        // Yahoo Finance symbol
  name:         string;        // Arabic name
  sector:       string;        // Sector Arabic
  type:         StockType;
  tier:         StockTier;
  riskLevel:    RiskLevel;
  description:  string;        // One-line simple description
  whyPick:      string;        // Why we picked it — plain Arabic
  targetPct:    number;        // Target profit %
  stopPct:      number;        // Stop loss %
  holdPeriod:   string;        // Holding period description
  lastSignal:   SignalType;    // Pre-computed signal (updated on trading days)
  signalReason: string;        // Plain-Arabic reason for signal
  analysis: {
    summary: string;           // Short analysis in simple Arabic
    entryNote: string;         // When to enter
    exitNote: string;          // When to exit
    watchout: string;          // Risk warning in plain language
  };
}

// ================================================================
// أسهم المضاربة — TOP 10
// ================================================================
export const SPECULATION_STOCKS: StockDef[] = [
  {
    symbol: "2010",
    yfSymbol: "2010.SR",
    name: "سابك",
    sector: "البتروكيماويات",
    type: "speculation",
    tier: "قيادي",
    riskLevel: "متوسط",
    description: "أكبر شركة بتروكيماويات في العالم — سيولة عالية جداً",
    whyPick: "سيولة يومية ضخمة · يتحرك مع أسعار النفط · مناسب للمضاربة اليومية",
    targetPct: 4.0,
    stopPct: 1.8,
    holdPeriod: "يوم إلى أسبوع",
    lastSignal: "دخول",
    signalReason: "السهم فوق متوسطه المتحرك وحجم التداول مرتفع",
    analysis: {
      summary: "سابك سهم قيادي ضخم — يتحرك بهدوء لكن بثبات. مناسب لمن يريد صفقة مضاربة آمنة نسبياً بسيولة عالية.",
      entryNote: "ادخل عند فتح السوق إذا كان السعر قريباً من سعر الإغلاق السابق أو أعلى منه قليلاً.",
      exitNote: "اخرج عند الوصول للهدف الأول فوراً — لا تنتظر أكثر.",
      watchout: "يتأثر بشدة بأسعار النفط العالمية — إذا انخفض النفط ابق بعيداً.",
    },
  },
  {
    symbol: "1120",
    yfSymbol: "1120.SR",
    name: "مصرف الراجحي",
    sector: "البنوك",
    type: "speculation",
    tier: "قيادي",
    riskLevel: "منخفض",
    description: "أكبر بنك إسلامي — تحركات سريعة عند الأخبار والنتائج",
    whyPick: "أعلى سيولة في القطاع المصرفي · مؤشر رئيسي للسوق · فرص يومية منتظمة",
    targetPct: 3.5,
    stopPct: 1.5,
    holdPeriod: "يوم إلى 3 أيام",
    lastSignal: "انتظر",
    signalReason: "السهم في منطقة مقاومة — انتظر كسرها أو تراجعاً خفيفاً للدخول",
    analysis: {
      summary: "الراجحي سهم قوي ومستقر — الخطر فيه منخفض نسبياً لكن الهدف أيضاً معقول. مثالي للمبتدئين في المضاربة.",
      entryNote: "الدخول المثالي بعد أي تراجع 1-2% من القمة الأخيرة مع بداية الارتداد.",
      exitNote: "اخرج فوراً عند الوصول لـ +3.5% — لا تتعلق بالسهم.",
      watchout: "قرارات الفائدة الأمريكية والأخبار المصرفية تؤثر عليه مباشرة.",
    },
  },
  {
    symbol: "2350",
    yfSymbol: "2350.SR",
    name: "المصافي",
    sector: "الطاقة",
    type: "speculation",
    tier: "خشاش",
    riskLevel: "عالي",
    description: "مصافي النفط — يتحرك بقوة مع أسعار النفط 5-10% في اليوم",
    whyPick: "أعلى تقلباً في القطاع · فرص ربح سريع · يتبع النفط مباشرة",
    targetPct: 6.0,
    stopPct: 2.5,
    holdPeriod: "يوم واحد فقط",
    lastSignal: "دخول",
    signalReason: "النفط يرتفع والسهم بدأ في التحرك صعوداً مع حجم تداول عالٍ",
    analysis: {
      summary: "المصافي سهم عالي الخطورة والمكافأة في نفس الوقت. يمكن أن يعطي 6-10% في يوم واحد لكنه يمكن أن ينزل بنفس السرعة.",
      entryNote: "ادخل في أول 30 دقيقة من الجلسة إذا فتح صاعداً مع حجم تداول مرتفع.",
      exitNote: "وقف الخسارة إلزامي — لا تنتظر إذا نزل 2.5% عن سعر الدخول.",
      watchout: "سهم عالي الخطورة جداً — لا تضع فيه أكثر من 20% من سيولتك.",
    },
  },
  {
    symbol: "2380",
    yfSymbol: "2380.SR",
    name: "بترو رابغ",
    sector: "البتروكيماويات",
    type: "speculation",
    tier: "خشاش",
    riskLevel: "عالي",
    description: "سهم متقلب جداً — فرص ربح سريع مع وقف خسارة صارم",
    whyPick: "تحركات 5-10% شائعة · سهم مضاربة كلاسيكي في السوق السعودي",
    targetPct: 7.0,
    stopPct: 3.0,
    holdPeriod: "يوم واحد فقط",
    lastSignal: "انتظر",
    signalReason: "السهم في مرحلة تذبذب — انتظر اتجاهاً واضحاً",
    analysis: {
      summary: "بترو رابغ من أكثر الأسهم تقلباً في السوق. يعطي فرص ربح كبيرة لكنه خطير جداً على المبتدئين.",
      entryNote: "ادخل فقط عند كسر مقاومة واضحة مع حجم تداول عالٍ جداً.",
      exitNote: "لا تنام على هذا السهم — أغلق صفقتك قبل نهاية الجلسة دائماً.",
      watchout: "خطير جداً للمبتدئين — ضع وقف الخسارة قبل الدخول بدون استثناء.",
    },
  },
  {
    symbol: "2160",
    yfSymbol: "2160.SR",
    name: "ينساب",
    sector: "البتروكيماويات",
    type: "speculation",
    tier: "متوسط" as any,
    riskLevel: "متوسط",
    description: "شركة بتروكيماويات ينبع — نمو ثابت وتحركات منتظمة",
    whyPick: "حركة تقنية قابلة للتوقع · يتبع قطاع البتروكيماويات بانتظام",
    targetPct: 5.0,
    stopPct: 2.0,
    holdPeriod: "يوم إلى 3 أيام",
    lastSignal: "دخول",
    signalReason: "كسر مقاومة مع حجم تداول أعلى من المتوسط",
    analysis: {
      summary: "ينساب سهم مضاربة ممتاز — تحركاته منتظمة وقابلة للقراءة، مناسب للمتداولين الذين يتعلمون.",
      entryNote: "الدخول المثالي عند تراجع خفيف للمتوسط المتحرك ثم الارتداد منه.",
      exitNote: "الهدف +5% أو نهاية الأسبوع أيهما أسبق.",
      watchout: "تأثر بأسعار النفط — تابع النفط قبل الدخول.",
    },
  },
  {
    symbol: "1020",
    yfSymbol: "1020.SR",
    name: "بنك الرياض",
    sector: "البنوك",
    type: "speculation",
    tier: "قيادي",
    riskLevel: "منخفض",
    description: "بنك قيادي — استقرار نسبي مع فرص تداول يومية منتظمة",
    whyPick: "خطورة منخفضة للمضاربة · سيولة عالية · أداء منتظم",
    targetPct: 3.0,
    stopPct: 1.5,
    holdPeriod: "يوم إلى أسبوع",
    lastSignal: "دخول",
    signalReason: "السهم عند منطقة دعم قوية مع بداية ارتداد",
    analysis: {
      summary: "بنك الرياض خيار آمن للمضاربة — الربح أقل لكن الخسارة محدودة. مثالي للمبتدئين.",
      entryNote: "ادخل عند الدعم وضع وقف الخسارة 1.5% تحته مباشرة.",
      exitNote: "اخرج عند +3% ولا تطمع في أكثر.",
      watchout: "قرارات الفائدة السعودية والأمريكية قد تؤثر على البنوك فجأة.",
    },
  },
  {
    symbol: "1810",
    yfSymbol: "1810.SR",
    name: "سبكيم",
    sector: "البتروكيماويات",
    type: "speculation",
    tier: "متوسط" as any,
    riskLevel: "متوسط",
    description: "شركة كيماويات متخصصة — حركة تقنية منتظمة",
    whyPick: "يتبع قطاع البتروكيماويات · حجم تداول كافٍ · مناسب للمضاربة المتوسطة",
    targetPct: 5.5,
    stopPct: 2.2,
    holdPeriod: "يوم إلى 3 أيام",
    lastSignal: "انتظر",
    signalReason: "السهم يتذبذب حول المتوسط — انتظر كسراً واضحاً",
    analysis: {
      summary: "سبكيم سهم جيد للمضاربة المتوسطة — يعطي 5-7% عند الصعود بشكل منتظم.",
      entryNote: "الدخول عند كسر مستوى مقاومة واضح مع حجم تداول مرتفع.",
      exitNote: "اخرج عند +5% أو إذا نزل إلى وقف الخسارة بدون تردد.",
      watchout: "أقل سيولة من سابك والراجحي — تأكد من حجم التداول قبل الدخول.",
    },
  },
  {
    symbol: "2060",
    yfSymbol: "2060.SR",
    name: "عجلان وإخوانه",
    sector: "التجزئة",
    type: "speculation",
    tier: "متوسط" as any,
    riskLevel: "متوسط",
    description: "شركة تجارة متنوعة — تحركات قوية في موسم النتائج",
    whyPick: "فرص ممتازة في موسم النتائج الفصلية · تقلبات جيدة للمضاربة",
    targetPct: 6.0,
    stopPct: 2.5,
    holdPeriod: "يوم إلى أسبوع",
    lastSignal: "دخول",
    signalReason: "اقتراب موسم النتائج مع حركة صاعدة في الأسهم الأخيرة",
    analysis: {
      summary: "عجلان وإخوانه يتحرك بقوة قبيل وبعد إعلان النتائج الفصلية — وقت الدخول مهم جداً.",
      entryNote: "افضل وقت للدخول: أسبوع قبل إعلان النتائج الفصلية.",
      exitNote: "اخرج في يوم الإعلان أو في اليوم التالي مباشرة.",
      watchout: "النتائج السلبية تؤدي لانخفاض حاد — تحقق من توقعات السوق قبل الدخول.",
    },
  },
  {
    symbol: "1211",
    yfSymbol: "1211.SR",
    name: "معادن",
    sector: "التعدين",
    type: "speculation",
    tier: "قيادي",
    riskLevel: "متوسط",
    description: "أكبر شركة تعدين — يتحرك مع أسعار الذهب والمعادن",
    whyPick: "سيولة عالية · مستقل عن النفط · فرص مضاربة مع الذهب",
    targetPct: 5.0,
    stopPct: 2.0,
    holdPeriod: "يوم إلى أسبوع",
    lastSignal: "دخول",
    signalReason: "الذهب في صعود ومعادن تتبعه مع حجم تداول مرتفع",
    analysis: {
      summary: "معادن سهم قيادي في قطاع مختلف — لا يتأثر بالنفط مما يجعله تنويعاً ممتازاً.",
      entryNote: "ادخل عند ارتفاع أسعار الذهب العالمية أو عند ظهور حجم تداول غير عادي.",
      exitNote: "اخرج عند الهدف +5% أو إذا انعكس الذهب للأسفل.",
      watchout: "يتأثر بأسعار المعادن العالمية وليس فقط السوق السعودي.",
    },
  },
  {
    symbol: "4261",
    yfSymbol: "4261.SR",
    name: "أبو عرابي للإيجار",
    sector: "الخدمات",
    type: "speculation",
    tier: "خشاش",
    riskLevel: "عالي",
    description: "سهم خشاش — تحركات 5-10% في اليوم لكن خطير جداً",
    whyPick: "أعلى نسبة تقلب · فرص ربح سريع جداً للمضاربين المتمرسين",
    targetPct: 8.0,
    stopPct: 3.0,
    holdPeriod: "يوم واحد فقط",
    lastSignal: "انتظر",
    signalReason: "السهم في تذبذب — انتظر إشارة اتجاه واضحة",
    analysis: {
      summary: "سهم خشاش عالي الخطورة — مناسب فقط للمضاربين ذوي الخبرة الذين يستطيعون مراقبة السهم بشكل مستمر.",
      entryNote: "ادخل فقط عند كسر واضح لمستوى مهم مع حجم تداول ضخم.",
      exitNote: "اخرج بمجرد الوصول للهدف — لا تنتظر أبداً.",
      watchout: "خطير جداً للمبتدئين — إذا لم تكن تفهم المضاربة جيداً تجنب هذا السهم.",
    },
  },
];

// ================================================================
// أسهم الاستثمار — TOP 10
// ================================================================
export const INVESTMENT_STOCKS: StockDef[] = [
  {
    symbol: "1140",
    yfSymbol: "1140.SR",
    name: "البنك الأهلي التجاري",
    sector: "البنوك",
    type: "investment",
    tier: "قيادي",
    riskLevel: "منخفض",
    description: "أكبر بنك في السعودية والشرق الأوسط — نمو ثابت وأرباح موزعة",
    whyPick: "أكبر بنك في المملكة · نمو أرباح ثابت · مدعوم بالرؤية 2030 · عوائد سنوية",
    targetPct: 35.0,
    stopPct: 12.0,
    holdPeriod: "6 إلى 12 شهراً",
    lastSignal: "دخول",
    signalReason: "القطاع المصرفي في نمو والسهم عند مستويات جيدة للدخول",
    analysis: {
      summary: "البنك الأهلي من أقوى الاستثمارات في السوق السعودي — نمو ثابت وأرباح موزعة كل عام، مناسب جداً للاستثمار طويل الأمد.",
      entryNote: "الدخول الآن مناسب — يمكنك الدخول على دفعات (30% الآن + 30% بعد شهر + 40% عند أي تراجع).",
      exitNote: "الخروج المثالي بعد 9-12 شهر أو عند وصول الهدف +35%.",
      watchout: "رفع أسعار الفائدة مفيد للبنوك لكن ركود اقتصادي قد يضر — تابع أخبار الاقتصاد.",
    },
  },
  {
    symbol: "7010",
    yfSymbol: "7010.SR",
    name: "الاتصالات السعودية STC",
    sector: "الاتصالات",
    type: "investment",
    tier: "عوائد",
    riskLevel: "منخفض",
    description: "شركة الاتصالات الأولى — أرباح ربع سنوية منتظمة",
    whyPick: "احتكار فعلي للاتصالات · توزيع أرباح كل 3 أشهر · طلب متزايد على الإنترنت",
    targetPct: 25.0,
    stopPct: 10.0,
    holdPeriod: "سنة إلى سنتين",
    lastSignal: "دخول",
    signalReason: "الشركة تنمو وتوزع أرباح منتظمة — وقت الدخول مناسب",
    analysis: {
      summary: "STC من أفضل الأسهم للاستثمار الهادئ — تأخذ أرباحك كل 3 أشهر وترى السهم ينمو تدريجياً.",
      entryNote: "ادخل الآن أو قبل موعد توزيع الأرباح الفصلي بأسبوعين.",
      exitNote: "لا تخرج إلا إذا احتجت المال أو وصل لهدف +25%.",
      watchout: "إذا دخل منافس جديد للسوق قد يؤثر على الشركة — لكن هذا احتمال بعيد.",
    },
  },
  {
    symbol: "1020",
    yfSymbol: "1020.SR",
    name: "بنك الرياض",
    sector: "البنوك",
    type: "investment",
    tier: "عوائد",
    riskLevel: "منخفض",
    description: "بنك قوي بعوائد جيدة — نمو ثابت في محفظة القروض",
    whyPick: "توزيع أرباح ثابت · نمو في القروض العقارية · مستفيد من رؤية 2030",
    targetPct: 30.0,
    stopPct: 12.0,
    holdPeriod: "6 إلى 12 شهراً",
    lastSignal: "دخول",
    signalReason: "نتائج جيدة والقطاع المصرفي ينمو",
    analysis: {
      summary: "بنك الرياض خيار استثماري قوي — يوزع أرباح جيدة والسهم ينمو مع نمو الاقتصاد السعودي.",
      entryNote: "الدخول مناسب الآن — ضع وقف خسارة 12% تحت سعر الدخول.",
      exitNote: "استهدف +30% في 12 شهر أو احتفظ طويلاً وخذ الأرباح الموزعة.",
      watchout: "أداء القروض التجارية يؤثر على البنك — تابع البيانات المالية الفصلية.",
    },
  },
  {
    symbol: "4190",
    yfSymbol: "4190.SR",
    name: "دله الحكمة الطبية",
    sector: "الرعاية الصحية",
    type: "investment",
    tier: "نمو",
    riskLevel: "متوسط",
    description: "قطاع الصحة ينمو بقوة مع رؤية 2030 — استثمار ممتاز",
    whyPick: "نمو قطاع الصحة ضمن رؤية 2030 · توسع في المستشفيات · طلب متزايد",
    targetPct: 45.0,
    stopPct: 15.0,
    holdPeriod: "سنة إلى 3 سنوات",
    lastSignal: "دخول",
    signalReason: "القطاع الصحي في نمو مستمر والسهم يظهر زخماً إيجابياً",
    analysis: {
      summary: "دله الحكمة من أفضل فرص النمو في السوق السعودي — قطاع الصحة سيظل ينمو مع زيادة عدد السكان وبرامج رؤية 2030.",
      entryNote: "ادخل على دفعتين — 50% الآن و50% عند أي تراجع 10-15%.",
      exitNote: "الهدف طويل الأمد +45% في 2-3 سنوات — الصبر هو المفتاح.",
      watchout: "الاستثمار في الصحة طويل الأمد — لا تضع فيه مال تحتاجه خلال السنة.",
    },
  },
  {
    symbol: "2300",
    yfSymbol: "2300.SR",
    name: "صافولا",
    sector: "الأغذية",
    type: "investment",
    tier: "عوائد",
    riskLevel: "منخفض",
    description: "شركة غذاء وتجزئة — استثمار دفاعي آمن في كل الظروف",
    whyPick: "الغذاء لا يتأثر بالأزمات الاقتصادية · حصة سوقية قوية · أرباح موزعة",
    targetPct: 20.0,
    stopPct: 10.0,
    holdPeriod: "سنة إلى سنتين",
    lastSignal: "انتظر",
    signalReason: "السهم عند مقاومة — انتظر تراجعاً خفيفاً للدخول بسعر أفضل",
    analysis: {
      summary: "صافولا سهم دفاعي ممتاز — إذا كنت تريد استثماراً هادئاً لا تقلق عليه هذا هو السهم المناسب.",
      entryNote: "انتظر حتى يتراجع 5-8% من سعره الحالي ثم ادخل — لا تتعجل.",
      exitNote: "الهدف +20% في 18-24 شهر، أو احتفظ وخذ الأرباح الموزعة.",
      watchout: "أسعار المواد الغذائية الخام العالمية قد تضغط على هوامش الربح.",
    },
  },
  {
    symbol: "1211",
    yfSymbol: "1211.SR",
    name: "معادن",
    sector: "التعدين",
    type: "investment",
    tier: "نمو",
    riskLevel: "متوسط",
    description: "أكبر شركة تعدين — ركيزة رؤية 2030 وثروات المملكة المعدنية",
    whyPick: "التعدين هو مستقبل السعودية · دعم حكومي كامل · احتياطيات ضخمة من الذهب",
    targetPct: 50.0,
    stopPct: 15.0,
    holdPeriod: "سنتان إلى 5 سنوات",
    lastSignal: "دخول",
    signalReason: "الذهب والمعادن في اتجاه صعودي والشركة تتوسع",
    analysis: {
      summary: "معادن فرصة استثمارية كبيرة على المدى البعيد — السعودية تحول اقتصادها نحو التعدين وهذه الشركة ستستفيد أكثر من غيرها.",
      entryNote: "ادخل على 3 دفعات على مدى 6 أشهر — هذا الاستثمار يحتاج صبراً.",
      exitNote: "الهدف +50% في 3-5 سنوات — إذا طلبت مالاً سريعاً هذا ليس الاختيار المناسب.",
      watchout: "استثمار طويل الأمد جداً — لا تدخل بمال قد تحتاجه.",
    },
  },
  {
    symbol: "1140",
    yfSymbol: "1140.SR",
    name: "البنك الأهلي التجاري",
    sector: "البنوك",
    type: "investment",
    tier: "قيادي",
    riskLevel: "منخفض",
    description: "أكبر بنك — الأقوى في السوق السعودي",
    whyPick: "رائد في القطاع المصرفي · نمو مستمر · عوائد ممتازة",
    targetPct: 35.0,
    stopPct: 12.0,
    holdPeriod: "6 إلى 12 شهراً",
    lastSignal: "دخول",
    signalReason: "القطاع المصرفي ينمو مع نمو الاقتصاد السعودي",
    analysis: {
      summary: "أقوى بنك في المملكة — إذا كنت مبتدئاً في الاستثمار ابدأ من هنا.",
      entryNote: "الدخول الآن مناسب جداً — البنك ينمو ويوزع أرباح.",
      exitNote: "الهدف +35% في 12 شهر.",
      watchout: "الجميع يستثمر في البنوك — المنافسة على الدخول تجعل التوقيت مهماً.",
    },
  },
  {
    symbol: "4280",
    yfSymbol: "4280.SR",
    name: "الأنماء للخدمات المالية",
    sector: "الخدمات المالية",
    type: "investment",
    tier: "نمو",
    riskLevel: "متوسط",
    description: "خدمات مالية إسلامية — نمو مع زيادة الاستثمارات في المملكة",
    whyPick: "نمو الخدمات المالية الإسلامية · استفادة من زيادة المستثمرين السعوديين",
    targetPct: 40.0,
    stopPct: 15.0,
    holdPeriod: "سنة إلى سنتين",
    lastSignal: "انتظر",
    signalReason: "السهم يحتاج تأكيداً إضافياً قبل الدخول",
    analysis: {
      summary: "الأنماء يستفيد من نمو التداول والاستثمار في السعودية — مع زيادة المستثمرين تنمو الشركة.",
      entryNote: "انتظر اتجاهاً صاعداً واضحاً ثم ادخل.",
      exitNote: "الهدف +40% في 2 سنة.",
      watchout: "حجم التداول على السهم نفسه قد يكون منخفضاً أحياناً.",
    },
  },
  {
    symbol: "2050",
    yfSymbol: "2050.SR",
    name: "صدارة للكيماويات",
    sector: "البتروكيماويات",
    type: "investment",
    tier: "نمو",
    riskLevel: "عالي",
    description: "شراكة أرامكو وDow — إمكانية نمو ضخمة جداً",
    whyPick: "طاقة إنتاجية ضخمة · نمو مرتقب قوي · دعم أرامكو الكامل",
    targetPct: 55.0,
    stopPct: 20.0,
    holdPeriod: "سنتان إلى 3 سنوات",
    lastSignal: "دخول",
    signalReason: "السهم في مستويات جيدة مع توقعات نمو قوية",
    analysis: {
      summary: "صدارة فرصة نمو ضخمة على المدى البعيد — شراكة أرامكو تعطيه قوة هائلة لكنه يحتاج صبراً.",
      entryNote: "ادخل بنسبة صغيرة (10-15% من محفظتك) وزد التدريجياً.",
      exitNote: "الهدف +55% في 3 سنوات — هذا استثمار طويل الأمد.",
      watchout: "عالي الخطورة للاستثمار — لا تضع فيه نسبة كبيرة من مدخراتك.",
    },
  },
  {
    symbol: "4002",
    yfSymbol: "4002.SR",
    name: "هرفي للأغذية",
    sector: "الأغذية",
    type: "investment",
    tier: "عوائد",
    riskLevel: "منخفض",
    description: "سلسلة مطاعم سعودية رائدة — نمو مع السياحة والترفيه",
    whyPick: "استفادة من رؤية 2030 في السياحة · توسع مستمر · عوائد توزيعات",
    targetPct: 30.0,
    stopPct: 12.0,
    holdPeriod: "سنة إلى سنتين",
    lastSignal: "دخول",
    signalReason: "قطاع الأغذية والمطاعم ينمو مع الترفيه في السعودية",
    analysis: {
      summary: "هرفي مستفيد مباشر من رؤية 2030 في السياحة والترفيه — كلما ازدادت الفعاليات والترفيه كلما زادت مبيعاتهم.",
      entryNote: "الدخول مناسب الآن مع الموسم السياحي القادم.",
      exitNote: "الهدف +30% في 12-18 شهر.",
      watchout: "يتأثر بحالة الاقتصاد العام وإنفاق المستهلكين.",
    },
  },
];

// Remove duplicates (1140 appears in both) — use index to deduplicate
export const ALL_STOCKS = [...SPECULATION_STOCKS, ...INVESTMENT_STOCKS];

export function getStockBySymbol(symbol: string): StockDef | undefined {
  return ALL_STOCKS.find((s) => s.symbol === symbol);
}

// Signal config for UI
export const SIGNAL_CONFIG: Record<SignalType, { label: string; color: string; bg: string; border: string; icon: string }> = {
  "دخول":  { label: "دخول الآن",   color: "text-green",  bg: "bg-[rgb(var(--green)/0.12)]",  border: "border-[rgb(var(--green)/0.35)]",  icon: "🟢" },
  "انتظر": { label: "انتظر",        color: "text-orange", bg: "bg-[rgb(var(--orange)/0.10)]", border: "border-[rgb(var(--orange)/0.30)]", icon: "🟡" },
  "خروج":  { label: "خروج الآن",   color: "text-red",    bg: "bg-[rgb(var(--red)/0.10)]",    border: "border-[rgb(var(--red)/0.30)]",    icon: "🔴" },
};

export const TIER_CONFIG: Record<string, { label: string; color: string }> = {
  "قيادي": { label: "سهم قيادي",  color: "text-gold-bright" },
  "نمو":   { label: "سهم نمو",    color: "text-blue" },
  "عوائد": { label: "سهم عوائد",  color: "text-green" },
  "خشاش":  { label: "خشاش ⚠",    color: "text-orange" },
};

export const RISK_CONFIG: Record<RiskLevel, { label: string; color: string }> = {
  "منخفض": { label: "خطورة منخفضة ✓", color: "text-green" },
  "متوسط": { label: "خطورة متوسطة",   color: "text-gold-bright" },
  "عالي":  { label: "خطورة عالية ⚠",  color: "text-red" },
};
